# Generated by Django 5.2.10 on 2026-01-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit'), ('brokerage', 'Brokerage'), ('other', 'Other')], default='checking', max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=32)),
                ('apy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('icon', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('points_balance', models.IntegerField(blank=True, null=True)),
                ('points_name', models.CharField(blank=True, max_length=120)),
                ('points_value', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('cashback_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rewards_this_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cashback_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('color', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16)),
                ('next_billing', models.DateField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(default='active', max_length=32)),
            ],
        ),
    ]
